name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: "1.24"
  REGISTRY: ghcr.io

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Install cosign
      uses: sigstore/cosign-installer@v3
      with:
        cosign-release: 'v2.2.4'

    - name: Install syft
      uses: anchore/sbom-action/download-syft@v0
      with:
        syft-version: 'v1.9.0'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Run tests with coverage
      run: |
        go test ./... -race -coverprofile=coverage.out
        go tool cover -func=coverage.out

    - name: Run security checks
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

    - name: Upload SBOM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sbom-artifacts
        path: |
          dist/*.sbom.json
        retention-days: 90

    - name: Upload signatures
      uses: actions/upload-artifact@v4
      with:
        name: signature-artifacts
        path: |
          dist/*.cert
          dist/*.sig
        retention-days: 90
